### PR TITLE
Explicitly import etcdraft

### PR DESCRIPTION
**Pull request by yacovm**
Signed-off-by: Yacov Manevich <yacovm@il.ibm.com>

### CODE REVIEW

**Comment by adecaro** [comment]
Why do we need this?

**Comment by yacovm** [comment]
> Why do we need this?

Otherwise the integration tests don't run when it attempts to build the fabric nodes via `go build`

**Comment by adecaro** [comment]
Why is that?

**Comment by adecaro** [comment]
Does this create a dependency to a specific fabric version?

**Comment by yacovm** [comment]
> Does this create a dependency to a specific fabric version?

Of course it does.

**Pull request closed without merging**
