### PR TITLE
Documentation for FTS_PATH changed as copy paste won't work

### PR DESCRIPTION
**Pull request by rajat-dlt**
Signed-off-by: Rajat Sharma <connecttorajat@outlook.com>

### CODE REVIEW

**Comment by rajat-dlt** [comment]
@mbrandenburger could you please review this.

**Comment by mbrandenburger** [comment]
Seems we have the same "issue" also at the Fabric Smart Client (https://github.com/hyperledger-labs/fabric-smart-client#getting-started).

**Comment by rajat-dlt** [comment]
> Seems we have the same "issue" also at the Fabric Smart Client (https://github.com/hyperledger-labs/fabric-smart-client#getting-started).

Should I raise a PR for that as well ?

**Comment by mbrandenburger** [comment]
> Should I raise a PR for that as well ?

That would be fantastic!

**Comment by rajat-dlt** [comment]
> > Should I raise a PR for that as well ?
> 
> That would be fantastic!

Done. Thanks !!

**Pull request merged**
